### ISSUE TITLE
Any plans for providing TypeScript typings?

### ISSUE THREAD

**Issue by ali-kamalizade** [Moesif/moesif-express#21]
Hey Moesif team! I stumbled over Moesif and I already like it a lot, thanks for providing this great service.

Are there any plans to support [TypeScript](https://www.typescriptlang.org/)? With typings, it is easier to use Moesif in your IDE when you are using TypeScript. The typings can be published in this repository or in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by matthewoates** [comment]
Hi Ali, thanks for the suggestion.

There currently are no plans to add typings for TypeScript or Flow. I'll put this in our issue tracker. We'll definitely bump up the priority when / if there's more interest in this issue.
