### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by kochis** [Moesif/moesif-express#27]
Hello! Just a heads up, but it looks like the documentation at https://www.moesif.com/docs/server-integration/express/#update-users-in-batch might not be up to date with this repo (or vice-versa).

The call for the batch update should be:
```js
moesifMiddleware.updateUsersBatch(users, callback);
```

instead of:
```js
moesifMiddleware.updateUser(users, callback);
```

**Comment by dgilling** [comment]
Thanks @kochis for letting us know. Just deployed a doc update.
