### ISSUE TITLE
Provide concise TypeScript interfaces describing middleware options

### ISSUE THREAD

**Issue by igrek8** [Moesif/moesif-express#73]
At the moment, the typescript definitions do not help integrating your library. Options to middleware have everything as `any` which prevents anybody from discovering the library and integrating with it. It would be great if you can provide more consice typescript interfaces that describe your API.

<img width="729" alt="image" src="https://github.com/Moesif/moesif-nodejs/assets/7078731/faf9bdb2-b225-4287-919f-c764fbf868e0">

**Comment by xinghengwang** [comment]
please upgrade to 3.3.5. it is updated now.

**Comment by igrek8** [comment]
Thank you for looking into the issue. However, the types are still too wide and do not bring any value. Can you please specify more concrete types so that instead of `object` there will be types `express.Request`, `express.Response` etc. At the moment, `jsdoc` does not offer same type definitions as typescript would have offered. Perhaps, consider bringing in typescript.

In addition `eventModel: object` does not tell what kind of object is there. Please specify exact fields and types. We use this typing internally to resolve issues that I am reporting.

```ts
export interface MoesifReporterEvent {
  request: {
    time: string;
    uri: string;
    verb: string;
    headers: Record<string, string>;
    body?: unknown;
  };
  response?: {
    time: string;
    status: number;
    headers?: Record<string, string>;
    body?: unknown;
  };
  user_id?: string;
  company_id?: string;
  metadata?: unknown;
}
```

**Comment by xinghengwang** [comment]
Understood. Yes. agree that ultimately rebuild this library from ground up in Typescript is probably the best solution. Current type declaration is basically tacked on to this javascript library using auto generated tools.  It is on our roadmap to have an typescript version, but migration is a big undertake, it will take time, hope you understand.

**Comment by ihadabs** [comment]
@xinghengwang any update?

**Comment by xinghengwang** [comment]
Sorry, at this stage, still only basic Typescript types. Rebuiding is big undertake at this time.
